name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # GitHub spins up a Linux machine
    steps:
      - uses: actions/checkout@v3   # copies your repo code onto that machine
      - uses: actions/setup-node@v3 # installs Node.js version 18
        with:
          node-version: '18'
      - run: npm install # installs packages (fails — no package.json)
      - run: npm test    # runs tests (fails — no tests)
      # test trigger 1
